"""Mock data for development and presentations."""
from datetime import datetime, timedelta
import uuid

# ═══════════════════════════════════════════════════════════════════════════════
# ORGANIZATIONS - GLOBAL + NATIONAL
# ═══════════════════════════════════════════════════════════════════════════════

MOCK_ORGANIZATIONS_EXTENDED = [
    # NACIONALES
    {
        "id": "org-001",
        "name": "ICBF - Instituto Colombiano de Bienestar Familiar",
        "country": "Colombia",
        "org_type": "Público",
        "invests_colombia": True,
        "invests_latam": False,
        "access_type": "convocatoria",
        "strategic_obj": "capital",
        "general_objective": "Fortalecer programas de atención a primera infancia en Colombia",
        "aeiotu_role": "Implementador",
        "has_history": True,
        "website": "https://www.icbf.gov.co",
    },
    {
        "id": "org-002",
        "name": "Ministerio de Educación Nacional",
        "country": "Colombia",
        "org_type": "Público",
        "invests_colombia": True,
        "invests_latam": False,
        "access_type": "relacional",
        "strategic_obj": "capital",
        "general_objective": "Mejorar la calidad de educación inicial en el país",
        "aeiotu_role": "Asesor técnico",
        "has_history": True,
        "website": "https://www.mineducacion.gov.co",
    },
    {
        "id": "org-003",
        "name": "CAFAM - Caja de Compensación Familiar",
        "country": "Colombia",
        "org_type": "Caja de Compensación",
        "invests_colombia": True,
        "invests_latam": False,
        "access_type": "mixto",
        "strategic_obj": "exportacion_modelo",
        "general_objective": "Expandir programas de cuidado infantil a afiliados",
        "aeiotu_role": "Socio operativo",
        "has_history": True,
        "website": "https://www.cafam.com.co",
    },
    {
        "id": "org-004",
        "name": "Fundación Cargill",
        "country": "Colombia",
        "org_type": "Filantropía",
        "invests_colombia": True,
        "invests_latam": True,
        "access_type": "relacional",
        "strategic_obj": "capital",
        "general_objective": "Invertir en educación y desarrollo rural",
        "aeiotu_role": "Financiador",
        "has_history": True,
        "website": "https://www.cargill.com",
    },
    # GLOBALES - MULTILATERALES
    {
        "id": "org-005",
        "name": "Banco Interamericano de Desarrollo (BID)",
        "country": "Multinacional",
        "org_type": "Multilateral",
        "invests_colombia": True,
        "invests_latam": True,
        "access_type": "convocatoria",
        "strategic_obj": "capital",
        "general_objective": "Financiar proyectos de desarrollo integral en América Latina",
        "aeiotu_role": "Financiador",
        "has_history": True,
        "website": "https://www.iadb.org",
    },
    {
        "id": "org-006",
        "name": "LEGO Foundation",
        "country": "Dinamarca",
        "org_type": "Filantropía",
        "invests_colombia": False,
        "invests_latam": True,
        "access_type": "relacional",
        "strategic_obj": "capital",
        "general_objective": "Transformación de la educación inicial en el mundo",
        "aeiotu_role": "Financiador principal",
        "has_history": True,
        "website": "https://www.legofoundation.com",
    },
    {
        "id": "org-007",
        "name": "Grand Challenges Canada",
        "country": "Canadá",
        "org_type": "Filantropía",
        "invests_colombia": False,
        "invests_latam": True,
        "access_type": "convocatoria",
        "strategic_obj": "capital",
        "general_objective": "Desafíos globales y soluciones innovadoras",
        "aeiotu_role": "Financiador",
        "has_history": True,
        "website": "https://www.grandchallenges.ca",
    },
    {
        "id": "org-008",
        "name": "Fundación Hilton",
        "country": "Estados Unidos",
        "org_type": "Filantropía",
        "invests_colombia": False,
        "invests_latam": True,
        "access_type": "relacional",
        "strategic_obj": "capital",
        "general_objective": "Filantropia para la transformación global",
        "aeiotu_role": "Financiador",
        "has_history": True,
        "website": "https://www.hiltonfoundation.org",
    },
    {
        "id": "org-009",
        "name": "UNICEF - Fondo de Naciones Unidas para la Infancia",
        "country": "Multinacional",
        "org_type": "Multilateral",
        "invests_colombia": True,
        "invests_latam": True,
        "access_type": "convocatoria",
        "strategic_obj": "capital",
        "general_objective": "Protección y derechos de la infancia en el mundo",
        "aeiotu_role": "Aliado",
        "has_history": False,
        "website": "https://www.unicef.org",
    },
    {
        "id": "org-010",
        "name": "ONU Mujeres - Entidad de las Naciones Unidas para la Igualdad",
        "country": "Multinacional",
        "org_type": "Multilateral",
        "invests_colombia": True,
        "invests_latam": True,
        "access_type": "relacional",
        "strategic_obj": "capital",
        "general_objective": "Empoderamiento de mujeres y niñas",
        "aeiotu_role": "Aliado potencial",
        "has_history": False,
        "website": "https://www.unwomen.org",
    },
    {
        "id": "org-011",
        "name": "Fundación Ford",
        "country": "Estados Unidos",
        "org_type": "Filantropía",
        "invests_colombia": False,
        "invests_latam": True,
        "access_type": "relacional",
        "strategic_obj": "capital",
        "general_objective": "Avanzar el interés público en todo el mundo",
        "aeiotu_role": "Financiador potencial",
        "has_history": False,
        "website": "https://www.fordfoundation.org",
    },
    {
        "id": "org-012",
        "name": "Fundación Bill & Melinda Gates",
        "country": "Estados Unidos",
        "org_type": "Filantropía",
        "invests_colombia": False,
        "invests_latam": True,
        "access_type": "convocatoria",
        "strategic_obj": "capital",
        "general_objective": "Reducción de pobreza y mejora de salud global",
        "aeiotu_role": "Financiador potencial",
        "has_history": False,
        "website": "https://www.gatesfoundation.org",
    },
    {
        "id": "org-013",
        "name": "GIZ - Agencia de Cooperación Alemana",
        "country": "Alemania",
        "org_type": "Multilateral",
        "invests_colombia": True,
        "invests_latam": True,
        "access_type": "relacional",
        "strategic_obj": "capital",
        "general_objective": "Cooperación técnica para desarrollo sostenible",
        "aeiotu_role": "Aliado",
        "has_history": False,
        "website": "https://www.giz.de",
    },
    {
        "id": "org-014",
        "name": "CAF - Banco de Desarrollo de América Latina",
        "country": "Multinacional",
        "org_type": "Multilateral",
        "invests_colombia": True,
        "invests_latam": True,
        "access_type": "convocatoria",
        "strategic_obj": "capital",
        "general_objective": "Promover el desarrollo sostenible en América Latina",
        "aeiotu_role": "Aliado potencial",
        "has_history": False,
        "website": "https://www.caf.com",
    },
    {
        "id": "org-015",
        "name": "Fundación Telefónica",
        "country": "España",
        "org_type": "Filantropía",
        "invests_colombia": False,
        "invests_latam": True,
        "access_type": "relacional",
        "strategic_obj": "capital",
        "general_objective": "Transformación digital e inclusión social",
        "aeiotu_role": "Financiador potencial",
        "has_history": False,
        "website": "https://www.fundaciontelefonica.com",
    },
    {
        "id": "org-016",
        "name": "Fondo Global para la Educación (Global Fund for Education)",
        "country": "Estados Unidos",
        "org_type": "Filantropía",
        "invests_colombia": False,
        "invests_latam": True,
        "access_type": "convocatoria",
        "strategic_obj": "capital",
        "general_objective": "Acceso equitativo a educación de calidad",
        "aeiotu_role": "Financiador potencial",
        "has_history": False,
        "website": "https://www.globalfund4education.org",
    },
    {
        "id": "org-017",
        "name": "Luminate - Iniciativa por la Apertura Cívica",
        "country": "Multinacional",
        "org_type": "Filantropía",
        "invests_colombia": False,
        "invests_latam": True,
        "access_type": "relacional",
        "strategic_obj": "capital",
        "general_objective": "Ampliar cívica abierta y participación ciudadana",
        "aeiotu_role": "Aliado potencial",
        "has_history": False,
        "website": "https://www.luminateinitiative.org",
    },
    {
        "id": "org-018",
        "name": "Save the Children International",
        "country": "Reino Unido",
        "org_type": "ONG Internacional",
        "invests_colombia": True,
        "invests_latam": True,
        "access_type": "relacional",
        "strategic_obj": "capital",
        "general_objective": "Derechos y bienestar de los niños",
        "aeiotu_role": "Aliado potencial",
        "has_history": False,
        "website": "https://www.savethechildren.org",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# OPPORTUNITIES / CONVOCATORIAS
# ═══════════════════════════════════════════════════════════════════════════════

MOCK_OPPORTUNITIES = [
    {
        "id": str(uuid.uuid4()),
        "title": "LEGO Foundation - Programa de Transformación en Educación Inicial 2026",
        "description": "Financiamiento para programas innovadores de primera infancia con enfoque en equidad y sostenibilidad. Buscan modelos replicables en América Latina.",
        "funder_id": "org-006",
        "funder_name": "LEGO Foundation",
        "amount_min_cop": 800_000_000,
        "amount_max_cop": 2_500_000_000,
        "deadline": (datetime.now() + timedelta(days=45)).isoformat(),
        "url_rfp": "https://www.legofoundation.com/grants/2026",
        "url_source": "https://www.legofoundation.com/grants",
        "source_name": "manual",
        "org_website": "https://www.legofoundation.com",
        "org_email": "grants@legofoundation.com",
        "org_email_verified": True,
        "ceo_name": "Jørgen Vig Knudstorp",
        "ceo_title": "Chairman",
        "ceo_email": "jvk@legofoundation.com",
        "ceo_email_verified": True,
        "ceo_linkedin_url": "https://linkedin.com/in/jvk",
        "market_window": "funding_global",
        "capital_type": "grant",
        "score_total": 9,
        "score_details": {
            "c1": 2,
            "c2": 2,
            "c3": 2,
            "c4": 2,
            "c5": 1,
            "llm_justification": "Alineación perfecta con modelo ECD de aeioTU. Financiador histórico con relación establecida."
        },
        "decision": "go",
        "urgency": "high",
        "status": "reviewed",
        "detected_at": (datetime.now() - timedelta(days=5)).isoformat(),
    },
    {
        "id": str(uuid.uuid4()),
        "title": "ICBF - Mejoramiento de Calidad en Centros de Desarrollo Infantil",
        "description": "Convocatoria nacional para fortalecer la calidad educativa en CDI públicos. Presupuesto 2026 del ICBF para transformación pedagógica.",
        "funder_id": "org-001",
        "funder_name": "ICBF - Instituto Colombiano de Bienestar Familiar",
        "amount_min_cop": 500_000_000,
        "amount_max_cop": 1_500_000_000,
        "deadline": (datetime.now() + timedelta(days=22)).isoformat(),
        "url_rfp": "https://www.icbf.gov.co/convocatorias/2026/cdi",
        "url_source": "https://www.icbf.gov.co/convocatorias",
        "source_name": "nacional_colombia",
        "org_website": "https://www.icbf.gov.co",
        "org_email": "convocatorias@icbf.gov.co",
        "org_email_verified": True,
        "ceo_name": "Lina María Arbeláez",
        "ceo_title": "Directora General",
        "ceo_email": "lmarbelaez@icbf.gov.co",
        "ceo_email_verified": True,
        "ceo_linkedin_url": "https://linkedin.com/in/linamariaarbelaez",
        "market_window": "funding_colombia",
        "capital_type": "grant",
        "score_total": 8,
        "score_details": {
            "c1": 2,
            "c2": 2,
            "c3": 2,
            "c4": 2,
            "c5": 0,
            "llm_justification": "Excelente alineación con modelo. Viabilidad operativa garantizada. Ticket dentro de rango ideal."
        },
        "decision": "go",
        "urgency": "high",
        "status": "reviewed",
        "detected_at": (datetime.now() - timedelta(days=3)).isoformat(),
    },
    {
        "id": str(uuid.uuid4()),
        "title": "BID - Fondo de Innovación en Educación Inicial América Latina",
        "description": "Línea de financiamiento multilateral para proyectos innovadores en ECD. Enfoque en gobiernos subnacionales y OSC.",
        "funder_id": "org-005",
        "funder_name": "Banco Interamericano de Desarrollo (BID)",
        "amount_min_cop": 2_000_000_000,
        "amount_max_cop": 5_000_000_000,
        "deadline": (datetime.now() + timedelta(days=60)).isoformat(),
        "url_rfp": "https://www.iadb.org/convocatorias/educacion-inicial-2026",
        "url_source": "https://www.iadb.org/es/convocatorias",
        "source_name": "bid",
        "org_website": "https://www.iadb.org",
        "org_email": "oportunidades@iadb.org",
        "org_email_verified": True,
        "ceo_name": "Ilan Goldfajn",
        "ceo_title": "President",
        "ceo_email": "igoldfajn@iadb.org",
        "ceo_email_verified": True,
        "ceo_linkedin_url": "https://linkedin.com/in/ilangoldfajn",
        "market_window": "funding_global",
        "capital_type": "grant",
        "score_total": 7,
        "score_details": {
            "c1": 2,
            "c2": 2,
            "c3": 2,
            "c4": 1,
            "c5": 0,
            "llm_justification": "Alineación estratégica fuerte. Plazo amplio. Ticket máximo superior al rango ideal pero factible."
        },
        "decision": "go",
        "urgency": "medium",
        "status": "reviewed",
        "detected_at": (datetime.now() - timedelta(days=10)).isoformat(),
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Grand Challenges Canada - Desafíos en Primera Infancia",
        "description": "Convocatoria abierta para soluciones innovadoras en educación inicial. Priorizan modelos escalables y sostenibles.",
        "funder_id": "org-007",
        "funder_name": "Grand Challenges Canada",
        "amount_min_cop": 300_000_000,
        "amount_max_cop": 1_200_000_000,
        "deadline": (datetime.now() + timedelta(days=35)).isoformat(),
        "url_rfp": "https://www.grandchallenges.ca/early-childhood-2026",
        "url_source": "https://www.grandchallenges.ca",
        "source_name": "manual",
        "org_website": "https://www.grandchallenges.ca",
        "org_email": "grants@grandchallenges.ca",
        "org_email_verified": True,
        "ceo_name": "Arif Naved",
        "ceo_title": "Executive Director",
        "ceo_email": "anaved@grandchallenges.ca",
        "ceo_email_verified": False,
        "ceo_linkedin_url": "https://linkedin.com/in/arifnaved",
        "market_window": "funding_global",
        "capital_type": "grant",
        "score_total": 8,
        "score_details": {
            "c1": 2,
            "c2": 2,
            "c3": 2,
            "c4": 2,
            "c5": 0,
            "llm_justification": "Excelente alineación. Priorizan exactamente lo que aeioTU hace: modelos escalables."
        },
        "decision": "go",
        "urgency": "medium",
        "status": "reviewed",
        "detected_at": (datetime.now() - timedelta(days=7)).isoformat(),
    },
    {
        "id": str(uuid.uuid4()),
        "title": "MinEducación - Convocatoria de Acompañamiento Pedagógico 2026",
        "description": "Apoyo técnico a secretarías de educación para mejorar calidad educativa. Componente: formación de docentes en EI.",
        "funder_id": "org-002",
        "funder_name": "Ministerio de Educación Nacional",
        "amount_min_cop": 400_000_000,
        "amount_max_cop": 1_800_000_000,
        "deadline": (datetime.now() + timedelta(days=28)).isoformat(),
        "url_rfp": "https://www.mineducacion.gov.co/convocatorias/2026/acompanamiento",
        "url_source": "https://www.mineducacion.gov.co/convocatorias",
        "source_name": "nacional_colombia",
        "org_website": "https://www.mineducacion.gov.co",
        "org_email": "convocatorias@mineducacion.gov.co",
        "org_email_verified": True,
        "ceo_name": "Aurora Vergara",
        "ceo_title": "Ministra de Educación",
        "ceo_email": "avergara@mineducacion.gov.co",
        "ceo_email_verified": True,
        "ceo_linkedin_url": "https://linkedin.com/in/auroravergara",
        "market_window": "funding_colombia",
        "capital_type": "grant",
        "score_total": 7,
        "score_details": {
            "c1": 2,
            "c2": 1,
            "c3": 2,
            "c4": 2,
            "c5": 0,
            "llm_justification": "Alineación alta. Viabilidad garantizada. Menos enfoque en escalabilidad sistémica."
        },
        "decision": "pending",
        "urgency": "high",
        "status": "detected",
        "detected_at": (datetime.now() - timedelta(days=1)).isoformat(),
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Fundación Hilton - Iniciativas de Transformación Social",
        "description": "Financiamiento para organizaciones con impacto demostrado en reducción de pobreza. Enfoque en educación y desarrollo comunitario.",
        "funder_id": "org-008",
        "funder_name": "Fundación Hilton",
        "amount_min_cop": 600_000_000,
        "amount_max_cop": 2_000_000_000,
        "deadline": (datetime.now() + timedelta(days=90)).isoformat(),
        "url_rfp": "https://www.hiltonfoundation.org/grants/2026-social-impact",
        "url_source": "https://www.hiltonfoundation.org/grants",
        "source_name": "manual",
        "org_website": "https://www.hiltonfoundation.org",
        "org_email": "grants@hiltonfoundation.org",
        "org_email_verified": True,
        "ceo_name": "Connie Weaver",
        "ceo_title": "President",
        "ceo_email": "cweaver@hiltonfoundation.org",
        "ceo_email_verified": False,
        "ceo_linkedin_url": "https://linkedin.com/in/connieweaver",
        "market_window": "funding_global",
        "capital_type": "grant",
        "score_total": 6,
        "score_details": {
            "c1": 2,
            "c2": 1,
            "c3": 2,
            "c4": 1,
            "c5": 0,
            "llm_justification": "Alineación media. Enfoque más amplio en pobreza, no específicamente ECD."
        },
        "decision": "pending",
        "urgency": "low",
        "status": "detected",
        "detected_at": (datetime.now() - timedelta(days=15)).isoformat(),
    },
    # ADICIONALES GLOBALES
    {
        "id": str(uuid.uuid4()),
        "title": "UNICEF - Fortalecimiento de Sistemas de Protección Infantil",
        "description": "Programa global de UNICEF para fortalecer sistemas de protección y desarrollo integral de niños en países de renta baja y media.",
        "funder_id": "org-009",
        "funder_name": "UNICEF",
        "amount_min_cop": 1_000_000_000,
        "amount_max_cop": 3_000_000_000,
        "deadline": (datetime.now() + timedelta(days=75)).isoformat(),
        "url_rfp": "https://www.unicef.org/calls/2026-child-protection",
        "url_source": "https://www.unicef.org/calls",
        "source_name": "manual",
        "org_website": "https://www.unicef.org",
        "org_email": "programme@unicef.org",
        "org_email_verified": True,
        "ceo_name": "Catherine Russell",
        "ceo_title": "Executive Director",
        "ceo_email": "crussell@unicef.org",
        "ceo_email_verified": True,
        "ceo_linkedin_url": "https://linkedin.com/in/catherinerussell",
        "market_window": "funding_global",
        "capital_type": "grant",
        "score_total": 7,
        "score_details": {
            "c1": 2,
            "c2": 2,
            "c3": 2,
            "c4": 1,
            "c5": 0,
            "llm_justification": "Organización multilateral con foco en infancia. Alineación estratégica alta."
        },
        "decision": "go",
        "urgency": "medium",
        "status": "reviewed",
        "detected_at": (datetime.now() - timedelta(days=8)).isoformat(),
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Fundación Ford - Iniciativas de Educación y Equidad",
        "description": "Financiamiento para innovación educativa con enfoque en equidad. Prioriza modelos sistémicos de transformación.",
        "funder_id": "org-011",
        "funder_name": "Fundación Ford",
        "amount_min_cop": 800_000_000,
        "amount_max_cop": 2_500_000_000,
        "deadline": (datetime.now() + timedelta(days=55)).isoformat(),
        "url_rfp": "https://www.fordfoundation.org/grant-finder/equity-in-education",
        "url_source": "https://www.fordfoundation.org/grants",
        "source_name": "manual",
        "org_website": "https://www.fordfoundation.org",
        "org_email": "grants@fordfoundation.org",
        "org_email_verified": True,
        "ceo_name": "Darren Walker",
        "ceo_title": "President",
        "ceo_email": "dwalker@fordfoundation.org",
        "ceo_email_verified": True,
        "ceo_linkedin_url": "https://linkedin.com/in/darrenwalker",
        "market_window": "funding_global",
        "capital_type": "grant",
        "score_total": 8,
        "score_details": {
            "c1": 2,
            "c2": 2,
            "c3": 2,
            "c4": 2,
            "c5": 0,
            "llm_justification": "Excelente alineación. Enfoque en equidad y transformación sistémica."
        },
        "decision": "go",
        "urgency": "high",
        "status": "reviewed",
        "detected_at": (datetime.now() - timedelta(days=6)).isoformat(),
    },
    {
        "id": str(uuid.uuid4()),
        "title": "CAF - Fondo de Apoyo para Innovación en Primera Infancia",
        "description": "Financiamiento regional de CAF para innovación y escalamiento de modelos en ECD en América Latina.",
        "funder_id": "org-014",
        "funder_name": "CAF",
        "amount_min_cop": 1_200_000_000,
        "amount_max_cop": 4_000_000_000,
        "deadline": (datetime.now() + timedelta(days=50)).isoformat(),
        "url_rfp": "https://www.caf.com/convocatorias/2026/ecd-innovation",
        "url_source": "https://www.caf.com/convocatorias",
        "source_name": "manual",
        "org_website": "https://www.caf.com",
        "org_email": "oportunidades@caf.com",
        "org_email_verified": True,
        "ceo_name": "Mauricio Claver-Carone",
        "ceo_title": "President",
        "ceo_email": "mclaver@caf.com",
        "ceo_email_verified": True,
        "ceo_linkedin_url": "https://linkedin.com/in/mauricioclaver",
        "market_window": "funding_global",
        "capital_type": "grant",
        "score_total": 7,
        "score_details": {
            "c1": 2,
            "c2": 2,
            "c3": 2,
            "c4": 1,
            "c5": 1,
            "llm_justification": "Alineación fuerte. Banco regional con presencia en Colombia."
        },
        "decision": "go",
        "urgency": "high",
        "status": "reviewed",
        "detected_at": (datetime.now() - timedelta(days=4)).isoformat(),
    },
    {
        "id": str(uuid.uuid4()),
        "title": "GIZ - Cooperación para Educación Inicial Sostenible",
        "description": "Programa de cooperación técnica alemana para fortalecimiento de políticas públicas en primera infancia.",
        "funder_id": "org-013",
        "funder_name": "GIZ",
        "amount_min_cop": 500_000_000,
        "amount_max_cop": 1_500_000_000,
        "deadline": (datetime.now() + timedelta(days=40)).isoformat(),
        "url_rfp": "https://www.giz.de/cooperacion-2026-ecd",
        "url_source": "https://www.giz.de/cooperacion",
        "source_name": "manual",
        "org_website": "https://www.giz.de",
        "org_email": "cooperacion@giz.de",
        "org_email_verified": True,
        "ceo_name": "Bernd Schwalb",
        "ceo_title": "CEO",
        "ceo_email": "bschwalb@giz.de",
        "ceo_email_verified": False,
        "ceo_linkedin_url": "https://linkedin.com/in/berndschwalb",
        "market_window": "funding_global",
        "capital_type": "grant",
        "score_total": 7,
        "score_details": {
            "c1": 2,
            "c2": 2,
            "c3": 2,
            "c4": 1,
            "c5": 0,
            "llm_justification": "Agencia de cooperación con historia en educación en Colombia."
        },
        "decision": "pending",
        "urgency": "medium",
        "status": "detected",
        "detected_at": (datetime.now() - timedelta(days=5)).isoformat(),
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Save the Children - Iniciativa Global de Educación",
        "description": "Programa internacional de Save the Children para mejorar acceso y calidad de educación inicial.",
        "funder_id": "org-018",
        "funder_name": "Save the Children International",
        "amount_min_cop": 700_000_000,
        "amount_max_cop": 2_200_000_000,
        "deadline": (datetime.now() + timedelta(days=65)).isoformat(),
        "url_rfp": "https://www.savethechildren.org/grants/2026-education",
        "url_source": "https://www.savethechildren.org/grants",
        "source_name": "manual",
        "org_website": "https://www.savethechildren.org",
        "org_email": "grants@savethechildren.org",
        "org_email_verified": True,
        "ceo_name": "Inger Ashing",
        "ceo_title": "International CEO",
        "ceo_email": "iashing@savethechildren.org",
        "ceo_email_verified": False,
        "ceo_linkedin_url": "https://linkedin.com/in/ingerashing",
        "market_window": "funding_global",
        "capital_type": "grant",
        "score_total": 6,
        "score_details": {
            "c1": 2,
            "c2": 1,
            "c3": 2,
            "c4": 1,
            "c5": 0,
            "llm_justification": "ONG global con presencia en Colombia. Alineación media-alta."
        },
        "decision": "pending",
        "urgency": "low",
        "status": "detected",
        "detected_at": (datetime.now() - timedelta(days=12)).isoformat(),
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# CONTACTS / CONTACTOS
# ═══════════════════════════════════════════════════════════════════════════════

MOCK_CONTACTS = [
    {
        "id": str(uuid.uuid4()),
        "full_name": "Jørgen Vig Knudstorp",
        "title": "Chairman",
        "email": "jvk@legofoundation.com",
        "linkedin_url": "https://linkedin.com/in/jvk",
        "funder_id": "org-006",
        "funder_name": "LEGO Foundation",
        "aeiotu_connection": True,
        "source": "manual",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Lina María Arbeláez",
        "title": "Directora General",
        "email": "lmarbelaez@icbf.gov.co",
        "linkedin_url": "https://linkedin.com/in/linamariaarbelaez",
        "funder_id": "org-001",
        "funder_name": "ICBF",
        "aeiotu_connection": True,
        "source": "manual",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Aurora Vergara",
        "title": "Ministra de Educación",
        "email": "avergara@mineducacion.gov.co",
        "linkedin_url": "https://linkedin.com/in/auroravergara",
        "funder_id": "org-002",
        "funder_name": "Ministerio de Educación Nacional",
        "aeiotu_connection": True,
        "source": "manual",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "María Claudia López",
        "title": "Directora de Educación",
        "email": "mlopez@cafam.com.co",
        "linkedin_url": "https://linkedin.com/in/mariaclaudialopez",
        "funder_id": "org-003",
        "funder_name": "CAFAM",
        "aeiotu_connection": True,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Ilan Goldfajn",
        "title": "President",
        "email": "igoldfajn@iadb.org",
        "linkedin_url": "https://linkedin.com/in/ilangoldfajn",
        "funder_id": "org-005",
        "funder_name": "BID",
        "aeiotu_connection": False,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Arif Naved",
        "title": "Executive Director",
        "email": "anaved@grandchallenges.ca",
        "linkedin_url": "https://linkedin.com/in/arifnaved",
        "funder_id": "org-007",
        "funder_name": "Grand Challenges Canada",
        "aeiotu_connection": False,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Paulo Mateus",
        "title": "Director Educación Inicial",
        "email": "pmateus@fundacioncargill.org.co",
        "linkedin_url": "https://linkedin.com/in/paulomateus",
        "funder_id": "org-004",
        "funder_name": "Fundación Cargill",
        "aeiotu_connection": True,
        "source": "apollo",
    },
    # CONTACTOS GLOBALES
    {
        "id": str(uuid.uuid4()),
        "full_name": "Catherine Russell",
        "title": "Executive Director",
        "email": "crussell@unicef.org",
        "linkedin_url": "https://linkedin.com/in/catherinerussell",
        "funder_id": "org-009",
        "funder_name": "UNICEF",
        "aeiotu_connection": False,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Phumzile Mlambo-Ngcuka",
        "title": "Executive Director",
        "email": "plambo@unwomen.org",
        "linkedin_url": "https://linkedin.com/in/phumzilemlambo",
        "funder_id": "org-010",
        "funder_name": "ONU Mujeres",
        "aeiotu_connection": False,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Darren Walker",
        "title": "President",
        "email": "dwalker@fordfoundation.org",
        "linkedin_url": "https://linkedin.com/in/darrenwalker",
        "funder_id": "org-011",
        "funder_name": "Fundación Ford",
        "aeiotu_connection": False,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Mark Suzman",
        "title": "CEO",
        "email": "msuzman@gatesfoundation.org",
        "linkedin_url": "https://linkedin.com/in/marksuzman",
        "funder_id": "org-012",
        "funder_name": "Fundación Gates",
        "aeiotu_connection": False,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Bernd Schwalb",
        "title": "CEO",
        "email": "bschwalb@giz.de",
        "linkedin_url": "https://linkedin.com/in/berndschwalb",
        "funder_id": "org-013",
        "funder_name": "GIZ",
        "aeiotu_connection": False,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Mauricio Claver-Carone",
        "title": "President",
        "email": "mclaver@caf.com",
        "linkedin_url": "https://linkedin.com/in/mauricioclaver",
        "funder_id": "org-014",
        "funder_name": "CAF",
        "aeiotu_connection": False,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Inger Ashing",
        "title": "International CEO",
        "email": "iashing@savethechildren.org",
        "linkedin_url": "https://linkedin.com/in/ingerashing",
        "funder_id": "org-018",
        "funder_name": "Save the Children",
        "aeiotu_connection": False,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Joan Kyeyune",
        "title": "Regional Director Education",
        "email": "jkyeyune@fundaciontelefonica.com",
        "linkedin_url": "https://linkedin.com/in/joankyeyune",
        "funder_id": "org-015",
        "funder_name": "Fundación Telefónica",
        "aeiotu_connection": False,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Lisa Parkinson",
        "title": "Executive Director",
        "email": "lparkinson@globalfund4education.org",
        "linkedin_url": "https://linkedin.com/in/lisaparkinson",
        "funder_id": "org-016",
        "funder_name": "Global Fund for Education",
        "aeiotu_connection": False,
        "source": "apollo",
    },
    {
        "id": str(uuid.uuid4()),
        "full_name": "Dmitry Zubov",
        "title": "Director Operations",
        "email": "dzubov@luminateinitiative.org",
        "linkedin_url": "https://linkedin.com/in/dmitryzubov",
        "funder_id": "org-017",
        "funder_name": "Luminate",
        "aeiotu_connection": False,
        "source": "apollo",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# TENDERS / CONVOCATORIAS NACIONALES
# ═══════════════════════════════════════════════════════════════════════════════

MOCK_TENDERS = [
    {
        "id": str(uuid.uuid4()),
        "title": "SECOP - Servicios de Acompañamiento Pedagógico en CDI - Región Andina",
        "description": "Contratación de servicios especializados para acompañamiento pedagógico en 50 CDI públicos.",
        "source_name": "secop",
        "url_source": "https://www.secop.gov.co/buscador",
        "deadline": (datetime.now() + timedelta(days=20)).isoformat(),
        "amount_min_cop": 400_000_000,
        "amount_max_cop": 800_000_000,
        "budget_phase": "Presupuesto aprobado",
        "entity": "Gobernación del Huila",
        "entity_type": "Gobierno local",
        "access_type": "convocatoria",
        "market_window": "funding_colombia",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "ICBF - Consultoría para Diseño de Política de Calidad en Primera Infancia",
        "description": "Diseño e implementación de política pública para estándares de calidad en programas de ECD.",
        "source_name": "icbf_convocatorias",
        "url_source": "https://www.icbf.gov.co/convocatorias",
        "deadline": (datetime.now() + timedelta(days=35)).isoformat(),
        "amount_min_cop": 300_000_000,
        "amount_max_cop": 700_000_000,
        "budget_phase": "Presupuesto en evaluación",
        "entity": "ICBF",
        "entity_type": "Institución nacional",
        "access_type": "relacional",
        "market_window": "funding_colombia",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "MinEducación - Programa de Formación Docente en Educación Inicial",
        "description": "Formación de 500 docentes en metodologías innovadoras de ECD. Componentes: presencial y en línea.",
        "source_name": "mineducacion_rss",
        "url_source": "https://www.mineducacion.gov.co/convocatorias",
        "deadline": (datetime.now() + timedelta(days=45)).isoformat(),
        "amount_min_cop": 500_000_000,
        "amount_max_cop": 1_200_000_000,
        "budget_phase": "Presupuesto disponible",
        "entity": "Ministerio de Educación Nacional",
        "entity_type": "Institución nacional",
        "access_type": "convocatoria",
        "market_window": "funding_colombia",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "CAFAM - Consultoría de Transformación Digital en Programas de Cuidado",
        "description": "Implementación de plataforma digital para gestión y seguimiento de programas de cuidado infantil.",
        "source_name": "manual",
        "url_source": "https://www.cafam.com.co/oportunidades",
        "deadline": (datetime.now() + timedelta(days=25)).isoformat(),
        "amount_min_cop": 200_000_000,
        "amount_max_cop": 500_000_000,
        "budget_phase": "Presupuesto aprobado",
        "entity": "CAFAM",
        "entity_type": "Caja de compensación",
        "access_type": "relacional",
        "market_window": "funding_colombia",
    },
    # GLOBALES
    {
        "id": str(uuid.uuid4()),
        "title": "LEGO Foundation - Global Innovation in Early Childhood Development",
        "description": "International call for innovative approaches to ECD in Low and Middle Income Countries.",
        "source_name": "manual",
        "url_source": "https://www.legofoundation.com/grants/2026",
        "deadline": (datetime.now() + timedelta(days=70)).isoformat(),
        "amount_min_cop": 600_000_000,
        "amount_max_cop": 2_000_000_000,
        "budget_phase": "Budget available",
        "entity": "LEGO Foundation",
        "entity_type": "International Foundation",
        "access_type": "convocatoria",
        "market_window": "funding_global",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "UNICEF - Strengthening Early Learning Systems in Latin America",
        "description": "Regional grant for countries implementing quality improvements in early childhood education.",
        "source_name": "manual",
        "url_source": "https://www.unicef.org/calls/2026",
        "deadline": (datetime.now() + timedelta(days=55)).isoformat(),
        "amount_min_cop": 800_000_000,
        "amount_max_cop": 2_500_000_000,
        "budget_phase": "Budget approved",
        "entity": "UNICEF",
        "entity_type": "Multilateral",
        "access_type": "convocatoria",
        "market_window": "funding_global",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "BID - Programa de Innovación Educativa para América Latina",
        "description": "Convocatoria multilateral del BID para financiar proyectos innovadores en educación inicial.",
        "source_name": "manual",
        "url_source": "https://www.iadb.org/convocatorias/2026",
        "deadline": (datetime.now() + timedelta(days=80)).isoformat(),
        "amount_min_cop": 1_000_000_000,
        "amount_max_cop": 4_000_000_000,
        "budget_phase": "Budget available",
        "entity": "BID",
        "entity_type": "Multilateral",
        "access_type": "convocatoria",
        "market_window": "funding_global",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "CAF - Fondo para Innovación Educativa en Primera Infancia",
        "description": "Regional funding window of CAF for ECD innovation and scaling in Latin America.",
        "source_name": "manual",
        "url_source": "https://www.caf.com/convocatorias/2026",
        "deadline": (datetime.now() + timedelta(days=50)).isoformat(),
        "amount_min_cop": 1_200_000_000,
        "amount_max_cop": 3_500_000_000,
        "budget_phase": "Pending approval",
        "entity": "CAF",
        "entity_type": "Regional Bank",
        "access_type": "relacional",
        "market_window": "funding_global",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Ford Foundation - Equity in Early Childhood Education",
        "description": "International program supporting systemic change in early childhood education systems.",
        "source_name": "manual",
        "url_source": "https://www.fordfoundation.org/grants",
        "deadline": (datetime.now() + timedelta(days=45)).isoformat(),
        "amount_min_cop": 700_000_000,
        "amount_max_cop": 2_200_000_000,
        "budget_phase": "Budget available",
        "entity": "Ford Foundation",
        "entity_type": "International Foundation",
        "access_type": "relacional",
        "market_window": "funding_global",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "GIZ - Cooperación para Educación Inicial Sostenible",
        "description": "Technical cooperation program of German Agency for strengthening ECD policies.",
        "source_name": "manual",
        "url_source": "https://www.giz.de/cooperacion",
        "deadline": (datetime.now() + timedelta(days=60)).isoformat(),
        "amount_min_cop": 500_000_000,
        "amount_max_cop": 1_500_000_000,
        "budget_phase": "Budget available",
        "entity": "GIZ",
        "entity_type": "Technical Cooperation Agency",
        "access_type": "relacional",
        "market_window": "funding_global",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Save the Children - Global Education Initiative 2026",
        "description": "International program improving access and quality of early childhood education globally.",
        "source_name": "manual",
        "url_source": "https://www.savethechildren.org/grants",
        "deadline": (datetime.now() + timedelta(days=65)).isoformat(),
        "amount_min_cop": 600_000_000,
        "amount_max_cop": 2_000_000_000,
        "budget_phase": "Budget approved",
        "entity": "Save the Children",
        "entity_type": "International NGO",
        "access_type": "convocatoria",
        "market_window": "funding_global",
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Fundación Hilton - Global Transformation Initiatives",
        "description": "Funding for organizations demonstrating impact in poverty reduction with education focus.",
        "source_name": "manual",
        "url_source": "https://www.hiltonfoundation.org/grants",
        "deadline": (datetime.now() + timedelta(days=90)).isoformat(),
        "amount_min_cop": 500_000_000,
        "amount_max_cop": 1_800_000_000,
        "budget_phase": "Budget available",
        "entity": "Hilton Foundation",
        "entity_type": "International Foundation",
        "access_type": "relacional",
        "market_window": "funding_global",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# DASHBOARD METRICS
# ═══════════════════════════════════════════════════════════════════════════════

MOCK_DASHBOARD_METRICS = {
    "pipeline_value_cop": 10_500_000_000,
    "total_opportunities": 6,
    "go_opportunities": 4,
    "pending_opportunities": 2,
    "days_to_next_deadline": 22,
    "avg_score": 7.5,
    "contacts_verified": 5,
    "top_window": "funding_global",
    "top_funder": "LEGO Foundation",
}
