"""add convocation table

Revision ID: 61890b19ddbf
Revises: 011
Create Date: 2026-06-19 10:46:58.461563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '61890b19ddbf'
down_revision: Union[str, None] = '011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('url_convocation', sa.Text(), nullable=False),
    sa.Column('amount_min_cop', sa.BigInteger(), nullable=True),
    sa.Column('amount_max_cop', sa.BigInteger(), nullable=True),
    sa.Column('url_tor', sa.Text(), nullable=True),
    sa.Column('url_form', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('organization_website', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('data_completeness', sa.Integer(), nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['funders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_monitor_source_date'), table_name='scraper_monitor_log')
    op.drop_index(op.f('idx_monitor_status'), table_name='scraper_monitor_log')
    op.drop_table('scraper_monitor_log')
    op.drop_index(op.f('idx_endpoint_monitor_date'), table_name='endpoint_monitor_log')
    op.drop_index(op.f('idx_endpoint_monitor_status'), table_name='endpoint_monitor_log')
    op.drop_table('endpoint_monitor_log')
    op.drop_index(op.f('idx_scraper_metrics_date'), table_name='scraper_metrics')
    op.drop_index(op.f('idx_scraper_metrics_name_date'), table_name='scraper_metrics')
    op.drop_table('scraper_metrics')
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('contacts', 'aeiotu_connection',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('contacts', 'source',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'''apollo'''::text"))
    op.alter_column('contacts', 'role_category',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('contacts', 'priority_score',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('contacts', 'department',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('contacts', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('funders', 'has_history',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('funders', 'access_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('funders', 'strategic_obj',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('funders', 'aeiotu_role',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('funders', 'general_objective',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('funders', 'linkedin_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('funders', 'min_grant_cop',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('funders', 'max_grant_cop',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('funders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunities', 'url_tor',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('opportunities', 'url_form',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('opportunities', 'org_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('opportunities', 'ceo_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('opportunities', 'tender_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('opportunities', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'''detected'''::text"))
    op.alter_column('opportunities', 'region_target',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('opportunities', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_opp_deadline'), table_name='opportunities')
    op.drop_index(op.f('idx_opp_decision'), table_name='opportunities')
    op.drop_index(op.f('idx_opp_embedding'), table_name='opportunities', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_opp_score'), table_name='opportunities')
    op.drop_index(op.f('idx_opp_source'), table_name='opportunities')
    op.drop_index(op.f('idx_opp_status'), table_name='opportunities')
    op.drop_index(op.f('idx_opp_target_contact_date'), table_name='opportunities')
    op.drop_index(op.f('idx_opp_window'), table_name='opportunities')
    op.alter_column('score_log', 'scored_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('score_log', 'scored_by',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'''auto'''::text"))
    op.drop_index(op.f('idx_score_log_opp'), table_name='score_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_score_log_opp'), 'score_log', ['opportunity_id'], unique=False)
    op.alter_column('score_log', 'scored_by',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'''auto'''::text"))
    op.alter_column('score_log', 'scored_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_opp_window'), 'opportunities', ['market_window'], unique=False)
    op.create_index(op.f('idx_opp_target_contact_date'), 'opportunities', ['target_contact_date'], unique=False)
    op.create_index(op.f('idx_opp_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('idx_opp_source'), 'opportunities', ['source_name'], unique=False)
    op.create_index(op.f('idx_opp_score'), 'opportunities', [sa.literal_column('score_total DESC NULLS LAST')], unique=False)
    op.create_index(op.f('idx_opp_embedding'), 'opportunities', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_opp_decision'), 'opportunities', ['decision'], unique=False)
    op.create_index(op.f('idx_opp_deadline'), 'opportunities', ['deadline'], unique=False)
    op.alter_column('opportunities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunities', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunities', 'region_target',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('opportunities', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'''detected'''::text"))
    op.alter_column('opportunities', 'tender_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('opportunities', 'ceo_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('opportunities', 'org_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('opportunities', 'url_form',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('opportunities', 'url_tor',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('funders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('funders', 'max_grant_cop',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('funders', 'min_grant_cop',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('funders', 'linkedin_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('funders', 'general_objective',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('funders', 'aeiotu_role',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('funders', 'strategic_obj',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('funders', 'access_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('funders', 'has_history',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('contacts', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('contacts', 'department',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('contacts', 'priority_score',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('contacts', 'role_category',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('contacts', 'source',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'''apollo'''::text"))
    op.alter_column('contacts', 'aeiotu_connection',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('contacts', 'last_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('scraper_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('scraper_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('run_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_normalized', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_persisted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_skipped', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('errors_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('run_duration_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('scraper_metrics_pkey'))
    )
    op.create_index(op.f('idx_scraper_metrics_name_date'), 'scraper_metrics', ['scraper_name', 'run_date'], unique=False)
    op.create_index(op.f('idx_scraper_metrics_date'), 'scraper_metrics', ['run_date'], unique=False)
    op.create_table('endpoint_monitor_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('endpoint_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('http_status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('alerted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('endpoint_monitor_log_pkey'))
    )
    op.create_index(op.f('idx_endpoint_monitor_status'), 'endpoint_monitor_log', ['status'], unique=False)
    op.create_index(op.f('idx_endpoint_monitor_date'), 'endpoint_monitor_log', ['endpoint_name', 'checked_at'], unique=False)
    op.create_table('scraper_monitor_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('alerted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scraper_monitor_log_pkey'))
    )
    op.create_index(op.f('idx_monitor_status'), 'scraper_monitor_log', ['status'], unique=False)
    op.create_index(op.f('idx_monitor_source_date'), 'scraper_monitor_log', ['source_name', 'checked_at'], unique=False)
    op.drop_table('convocations')
    # ### end Alembic commands ###
